# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

even_sum = 2
fibonacci_list = [0, 1, 1, 2, 3]

def get_fib(list):
    return list[-1] + list[-2]

while fibonacci_list[-1] < 4000000:
    new_fib = get_fib(fibonacci_list)
    fibonacci_list.append(new_fib)
    if new_fib % 2 == 0:
        even_sum += new_fib

print(even_sum)
